routes/admin.php
<?php 

use Illuminate\Support\Facades\Route;

Route::get('admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.'], function () {

	Route::get('my_profile', 'MyProfileController@getMyProfile')->name('get_my_profile');
	Route::post('my_profile', 'MyProfileController@postMyProfile')->name('post_my_profile');

	Route::get('change_password', 'MyProfileController@getChangePassword')->name('get_change_password');
	Route::post('change_password', 'MyProfileController@postChangePassword')->name('post_change_password');
	Route::get('logout', 'MyProfileController@logout')->name('logout');

	Route::resource('customer_types', CustomerTypeController::class);
	Route::resource('users', UserController::class);
	Route::resource('customers', CustomerController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	
	if(!auth()->check())
    	return view('auth.login');

    return redirect('admin');
});

Auth::routes(['register' => false]);

app/Http/Controllers/CustomerTypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\CustomerType;
use Illuminate\Http\Request;

class CustomerTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        set_page_title(__('Customer Type'));
        set_create_title(__('Create New'));
        set_create_link(route('admin.customer_types.create'));
        set_table_column(['id', 'name', 'remark', 'status', '']);
        $rows = CustomerType::paginate(10);

        return view('admin.customer_type.index', compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        set_page_title(__('Customer Type'));
        set_create_title(__('Create New'));
        set_create_link(route('admin.customer_types.create'));

        return view('admin.customer_type.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data=[
            'name'=> $request->name,
            'remark'=> $request->remark,
            'status'=> $request->status
        ];
        CustomerType::create($data);
        return redirect(route('admin.customer_types.index'))->with([
            'message'=> __('Save Successfully!')
        ]);
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        set_page_title(__('Customer Type'));
        set_create_title(__('Create New'));
        set_create_link(route('admin.customer_types.create'));
        $row= CustomerType::find($id);

        return view('admin.customer_type.form', compact('row'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $row= CustomerType::find($id);
        $row->name= $request->name;
        $row->remark= $request->remark;
        $row->status= $request->status;
        $row->save();
        return redirect(route('admin.customer_types.index'))->with([
            'message'=> __('Update Successfully!')
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $row=CustomerType::find($id);
        if(!$row){
            return response()->json([
                'message'=>'Not Found!'
            ], 422);
        }
        $row->delete();
        return response()->json([
            'message'=> 'Delete Successfully!'
        ], 200);
    }
}

resources/views/admin/customer_type/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-3">
    <div class="row justify-content-center">
        <div class="col-md-12">
             <div class="card">
               <div class="card-header">
                  <h3 class="card-title">{{get_page_title()}}</h3>
                  <div class="card-tools">
                     <a href="{{ get_create_link() }}" class="btn btn-tool btn-sm text-primary">{!!get_create_title()!!}</a>
                  </div>
               </div>
               <div class="card-body">
                    {{Form::open(['url' => !empty($row->id)?route('admin.customer_types.update', $row->id):route('admin.customer_types.store'), 'method'=>!empty($row->id)?'PUT':'POST'])}}
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">{{__('Name')}}</label>
                            <div class="col-sm-10">
                                {{Form::text('name', $row->name??'', ['class'=>'form-control', 'id'=>'name', 'placeholder'=>__('Name'), 'required' => true])}}
                            </div>
                        </div>
                        <div class="form-group row">
                           <label for="remark" class="col-sm-2 col-form-label">{{__('Remark')}}</label>
                           <div class="col-sm-10">
                               {{Form::text('remark', $row->remark??'', ['class'=>'form-control', 'id'=>'remark', 'placeholder'=>__('Remark')])}}
                           </div>
                        </div>
                        <div class="form-group row">
                           <label for="status" class="col-sm-2 col-form-label">{{__('Status')}}</label>
                           <div class="col-sm-10">
                               {{Form::select('status', ['enabled'=>'Enabled', 'disabled'=> 'Disabled'], $row->status??'', ['class'=>'form-control', 'id'=>'status'])}}
                           </div>
                        </div>
                        <div class="col-md-12">
                            <button class="btn btn-primary float-right">{{__('Save')}}</button>
                            <a href="{{route('admin.customer_types.index')}}" class="btn btn-default float-right mr-1">{{__('Close')}}</a>
                        </div>
                    {{Form::close()}}
               </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/customer_type/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-3">
    <div class="row justify-content-center">
        <div class="col-md-12">
             <div class="card">
               <div class="card-header">
                  <h3 class="card-title">{{get_page_title()}}</h3>
                  <div class="card-tools">
                     <a href="{{ get_create_link() }}" class="btn btn-tool btn-sm text-primary">{!!get_create_title()!!}</a>
                  </div>
               </div>
               <div class="card-body p-0">
                  <table class="table table-striped projects">
                     <thead>
                        <tr>
                           @foreach(get_table_column() as $col)
                              <th class="text-uppercase">
                                 {{$col}}
                              </th>
                           @endforeach
                        </tr>
                     </thead>
                     <tbody>
                        @if ($rows->count())
                           @foreach ($rows as $row)
                           <tr class="item-{{$row->id}}">
                              <td>
                                 {{$row->id}}
                              </td>
                              <td>
                                 <a>
                                 {{$row->name}}
                                 </a>
                              </td>
                              <td>
                                 {{$row->remark}}
                              </td>
                              <td >
                                 <span class="badge badge-success text-uppercase">{{$row->status}}</span>
                              </td>
                              <td class="project-actions text-right">
                                 <a class="btn btn-info btn-sm" href="{{route('admin.customer_types.edit', $row->id)}}">
                                 <i class="fas fa-pencil-alt"></i>
                                 Edit
                                 </a>
                                 <a class="btn btn-danger btn-sm" href="#" data-id="{{ $row->id }}" onclick="deleteItem(this)" data-url="{{route('admin.customer_types.destroy', $row->id)}}">
                                 <i class="fas fa-trash"></i>
                                 Delete
                                 </a>
                              </td>
                           </tr> 
                           @endforeach
                        @else
                           <tr>
                              <td colspan="5" class="text-center">{{__('No data')}}</td>
                           </tr>
                        @endif
                     </tbody>
                  </table>
               </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script>
       $(document).ready(function(){
         // test();

       });
       function test(){
          alert(123);
       }
       function deleteItem(obj){
         var id = $(obj).data('id');
         var url = $(obj).data('url');
         var token = $('meta[name=csrf-token]').attr('content');
         $('.item-'+ id).remove();
         $.ajax({
            type:'delete', 
            url: url,
            data: {
               _token:token
            },
            dataType: 'json',
            success: function(result){
               console.log(result)
            },
            error: function(result){
               console.log(result)
            }
         }); 
       }
    </script>
@stop