routes/admin.php
<?php 

use Illuminate\Support\Facades\Route;

Route::get('admin', [App\Http\Controllers\HomeController::class, 'index'])->name('admin');

Route::group(['middleware' => 'auth', 'prefix' => 'admin', 'as' => 'admin.'], function () {

	Route::get('my_profile', 'MyProfileController@getMyProfile')->name('get_my_profile');
	Route::post('my_profile', 'MyProfileController@postMyProfile')->name('post_my_profile');

	Route::get('change_password', 'MyProfileController@getChangePassword')->name('get_change_password');
	Route::post('change_password', 'MyProfileController@postChangePassword')->name('post_change_password');
	Route::get('logout', 'MyProfileController@logout')->name('logout');

	Route::resource('customer_types', CustomerTypeController::class);
	Route::resource('users', UserController::class);
	Route::resource('customers', CustomerController::class);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	
	if(!auth()->check())
    	return view('auth.login');

    return redirect('admin');
});

Auth::routes(['register' => false]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    const SUPER_ADMIN_ID = 1;
    
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getBtnDeleteAttribute(){
        return '<a class="btn btn-danger btn-sm" href="'.route('admin.users.destroy', $this->id).'">
                    <i class="fas fa-trash"></i>
                '.__('Delete').'
                </a>';
    }

    public function getBtnEditAttribute(){
        return '<a class="btn btn-info btn-sm" href="'.$this->edit_link.'">
                    <i class="fas fa-pencil-alt"></i>
                '.__('Edit').'
                </a>';
    }

    public function getBtnShowAttribute(){
        return '<a class="btn btn-primary btn-sm" href="'.route('admin.users.show', $this->id).'">
                    <i class="fas fa-eye"></i>
                '.__('Show').'
                </a>';
    }

    public function getEditLinkAttribute(){
        return route('admin.users.edit', $this->id);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    	$limit = $request->get('limit', 10);

        set_page_title(__('User'));
        set_create_title(__('Create New'));
        set_create_link(route('admin.users.create'));
        set_table_column(['id', 'name', 'email', '']);
        set_link_list(route('admin.users.index'));

        $rows = User::paginate($limit)->withQueryString();
        return view('admin.users.index', compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        set_page_title(__('Create User'));
        set_create_title(__('Create New'));
        set_create_link(route('admin.users.create'));
        set_form_url(route('admin.users.store'));
        set_form_method('POST');
        set_link_list(route('admin.users.index'));

        return view('admin.users.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = validator()->make($request->all(),[
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password'=> 'required|min:6|max:32',
            'password_confirmation' => 'required|same:password|min:6|max:32',
        ]);
        if ($validator->fails()){
            return back()->with(['error' => $validator->errors()->first()])->withInput();
        }

        $row = new User();
        $row->name = $request->name;
        $row->email = $request->email;
        $row->password = bcrypt($request->password);
        $row->save();

        // Adding roles to a user
        $roles = $request->get('roles', []);
        $this->userSyncRoles($roles, $row);

        return redirect(route('admin.users.index'))->with(['success' => __('Saved Successfully!')]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $row = User::findOrFail((int)$id);

        set_page_title(__('Edit User'));
        set_create_title(__('Create New'));
        set_create_link(route('admin.users.create'));
        set_form_url(route('admin.users.update', $id));
        set_form_method('PUT');
        set_link_list(route('admin.users.index'));

        return view('admin.users.form', compact('row'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $row = User::findOrFail((int)$id);

        $validator = validator()->make($request->all(),[
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            // 'password'=> 'required|min:6|max:32',
            // 'password_confirmation' => 'required|same:password|min:6|max:32',
        ]);
        if ($validator->fails()){
            return back()->with(['error' => $validator->errors()->first()])->withInput();
        }

        if($id == super_admin_id()){
            return back()->with(['error' => __('Not allow to modify super admin information.')])->withInput();
        }

        $row->name = $request->name;
        $row->email = $request->email;
        $row->save();

        // Adding roles to a user
        $roles = $request->get('roles', []);
        $this->userSyncRoles($roles, $row);
        
        return redirect(route('admin.users.index'))->with(['success' => __('Updated Successfully!')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($id == super_admin_id()){
            return back()->with(['error' => __('Not allow to modify super admin information.')]);
        }

        $row = User::findOrFail((int)$id);

        $row->delete();
        return redirect(route('admin.users.index'))->with(['success' => __('Deleted Successfully!')]);
    }

    private function userSyncRoles($roles, $user){

        if(!empty($roles)){
            $roleIds = [];
            foreach ($roles as $role) {
                $roleIds[] = $role['id']??0;
            }
            $roleObjs = Role::find($roleIds);
            $user->syncRoles($roleObjs);
        }
    }
}

resources/views/admin/users/change_password.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="row">
        <div class="col-md-12">
            <h4 class="float-left">{{get_page_title()}}</h4>
        </div>
    </div>
@stop
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!!message_render()!!}
             <div class="card">
               <div class="card-header">
                  <h3 class="card-title">{{get_page_title()}}</h3>
               </div>
               <div class="card-body">
                    {{Form::open(['url'=>get_form_url(), 'method'=>get_form_method()])}}
                        <div class="form-group row">
                            <label for="current_password" class="col-sm-2 col-form-label">{{__('Current Password')}}</label>
                            <div class="col-sm-10">
                                {{Form::input('password', 'current_password', '', ['class'=>'form-control', 'id'=>'current_password', 'placeholder'=>__('Current Password'), 'required' => true])}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password" class="col-sm-2 col-form-label">{{__('Password')}}</label>
                            <div class="col-sm-10">
                                {{Form::input('password', 'password', '', ['class'=>'form-control', 'id'=>'password', 'placeholder'=>__('Password'), 'required' => true])}}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password_confirmation" class="col-sm-2 col-form-label">{{__('Password Confirmation')}}</label>
                            <div class="col-sm-10">
                                {{Form::input('password', 'password_confirmation', '', ['class'=>'form-control', 'id'=>'password_confirmation', 'placeholder'=>__('Password Confirmation'), 'required' => true])}}
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button class="btn btn-primary float-right">{{__('Save')}}</button>
                        </div>
                    {{Form::close()}}
               </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/form.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="row">
        <div class="col-md-12">
            <h4 class="float-left">{{get_page_title()}}</h4>
            <a href="{{ get_create_link() }}" class="btn btn-primary btn-sm float-right">{!!get_create_title()!!}</a>
        </div>
    </div>
@stop
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!!message_render()!!}
             <div class="card">
               <div class="card-header">
                  <h3 class="card-title">{{get_page_title()}}</h3>
               </div>
               <div class="card-body">
                    {{Form::open(['url'=>get_form_url(), 'method'=>get_form_method()])}}
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">{{__('Name')}}</label>
                            <div class="col-sm-10">
                                {{Form::text('name', $row->name??'', ['class'=>'form-control', 'id'=>'name', 'placeholder'=>__('Name'), 'required' => true])}}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                {{Form::email('email', $row->email??'', ['class'=>'form-control', 'id'=>'email', 'placeholder'=>__('Email'), 'required' => true])}}
                            </div>
                        </div>

                        @if(empty($row->id))
                            <div class="form-group row">
                                <label for="password" class="col-sm-2 col-form-label">{{__('Password')}}</label>
                                <div class="col-sm-10">
                                    {{Form::input('password', 'password', '', ['class'=>'form-control', 'id'=>'password', 'placeholder'=>__('Password'), 'required' => true])}}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password_confirmation" class="col-sm-2 col-form-label">{{__('Password Confirmation')}}</label>
                                <div class="col-sm-10">
                                    {{Form::input('password', 'password_confirmation', '', ['class'=>'form-control', 'id'=>'password_confirmation', 'placeholder'=>__('Password Confirmation'), 'required' => true])}}
                                </div>
                            </div>
                        @endif

                        <div class="col-md-12">
                            <button class="btn btn-primary float-right">{{__('Save')}}</button>
                            <a href="{{get_link_list()}}" class="btn btn-default float-right mr-1">{{__('Close')}}</a>
                        </div>
                    {{Form::close()}}
               </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="row">
        <div class="col-md-12">
            <h4 class="float-left">{{get_page_title()}}</h4>
            <a href="{{ get_create_link() }}" class="btn btn-primary btn-sm float-right">{!!get_create_title()!!}</a>
        </div>
    </div>
@stop
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!!message_render()!!}
             <div class="card">
               <div class="card-header">
                  <h3 class="card-title">{{get_page_title()}}</h3>
               </div>
               <div class="card-body">
                    {{Form::open(['url'=>get_link_list(), 'method'=>'GET'])}}
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                   @foreach(get_table_column() as $col)
                                      <th class="text-uppercase">
                                         {{$col}}
                                      </th>
                                   @endforeach
                                </tr>
                            </thead>
                            <tbody>
                                @if($rows->count())
                                   @foreach($rows as $row)
                                      <tr>
                                         <td>
                                            {!! $row->id !!}
                                         </td>
                                         <td>
                                            <a href="{{$row->edit_link}}">
                                                {!! $row->name !!}
                                            </a>
                                         </td>
                                         <td>
                                            {!! $row->email !!}
                                         </td>
                                         <td class="text-right">
                                            {!! $row->btn_show !!}
                                            {!! $row->btn_edit !!}
                                            @if($row->id != super_admin_id() && $row->id != auth()->id())
                                               {!! $row->btn_delete !!}
                                            @endif
                                         </td>
                                      </tr>
                                   @endforeach
                                @else
                                   <tr><td colspan="4">{{__('There is no data available.')}}</td></tr>
                                @endif
                            </tbody>
                        </table>
                    {{Form::close()}}
               </div>
               <div class="card-footer clearfix">
                    {!! $rows->render() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/users/my_profile.blade.php
@extends('layouts.app')
@section('content_header')
    <div class="row">
        <div class="col-md-12">
            <h4 class="float-left">{{get_page_title()}}</h4>
        </div>
    </div>
@stop
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!!message_render()!!}
             <div class="card">
               <div class="card-header">
                  <h3 class="card-title">{{get_page_title()}}</h3>
               </div>
               <div class="card-body">
                    {{Form::open(['url'=>get_form_url(), 'method'=>get_form_method()])}}
                        <div class="form-group row">
                            <label for="name" class="col-sm-2 col-form-label">{{__('Name')}}</label>
                            <div class="col-sm-10">
                                {{Form::text('name', auth()->user()->name??'', ['class'=>'form-control', 'id'=>'name', 'placeholder'=>__('Name'), 'required' => true])}}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                {{Form::email('email', auth()->user()->email??'', ['class'=>'form-control', 'id'=>'email', 'placeholder'=>__('Email'), 'required' => true])}}
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button class="btn btn-primary float-right">{{__('Save')}}</button>
                            <a href="{{get_link_list()}}" class="btn btn-default float-right mr-1">{{__('Close')}}</a>
                        </div>
                    {{Form::close()}}
               </div>
            </div>
        </div>
    </div>
</div>
@endsection